// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package workout

// Injectors from wire.go:

func HandlerInject() (Handler, error) {
	dynamoDB := newDynamoDB()
	workoutServiceImpl := newService(dynamoDB)
	handler := NewHandler(workoutServiceImpl)
	return handler, nil
}
